In [3]:
import streamlit as st
import requests
import json
import numpy as np
import pandas as pd

food_type = pd.read_csv('food_type.csv')

#import state city dict
state_city_path = '/Users/dima/code/Dimasaur/scorecast/frontend/state_city_dict.json'

with open('state_city_dict.json') as json_file:
    state_city_dict = json.load(json_file)

st.markdown("""### First, select the cuisine type you'd like to have in your restaurants ###""")

food_type = st.selectbox(
    label = "# Restaurant type #",
    options = food_type['food_type']
    )

st.markdown("""### Tell us now where you want your restaurant to be located ###""")

# First dropdown: Select state
selected_state = st.selectbox(
    "Select a State:",
    options=list(state_city_dict.keys()))  # List of states from the dictionary

    # Second dropdown: Select city based on selected state
if selected_state:
    # Get the list of cities for the selected state
    cities = state_city_dict[selected_state]

    # Create a dropdown for cities
    selected_city = st.selectbox(
        "Select a City:",
        options=list(cities)  # List of cities corresponding to the selected state
        )

submitted = st.button("Submit your preferences")

2024-09-02 15:06:21.167 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.195
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/dima/.pyenv/versions/scorecast/lib/python3.10/site-packages/ipykernel_launcher.py [ARGUMENTS]
2024-09-02 15:06:21.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.196 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.198 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.198 Session state does not function when running a script without `streamlit run`
2024-09-02 15:06:21.199 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.201 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-02 15:06:21.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [80]:
df_restaurants = pd.read_csv("/Users/dima/code/Dimasaur/scorecast/data/restaurants_ohe.csv")

df_restaurants.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,food_type_one_Indian,food_type_one_Italian,food_type_one_Japanese,food_type_one_Mexican,food_type_one_Sandwiches,food_type_one_Seafood,food_type_one_Steakhouses,food_type_one_Thai,food_type_one_Vietnamese,food_type_one_None
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,NaN,Tampa Bay,FL,33602,27.955269,-82.456320,4.0,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [79]:


# filter the of the same city and food type
df_filtered = df_restaurants[
    (df_restaurants["city"].astype(str).str.upper() == "PHILADELPHIA") &
    (df_restaurants[f"food_type_one_{'Italian'}"] == 1)
]

# get top 10 cities
df_sorted = df_filtered.sort_values('stars',ascending=False)
df_map_input = df_sorted[["name","latitude","longitude"]].reset_index()
del df_map_input['index']
df_map_input = df_map_input[:10]
df_map_input

                                  name   latitude  longitude
0                         Castellino's  39.972337 -75.129040
1           Mediterranean Banquet Hall  39.925306 -75.173291
2                   Fiorella's Sausage  39.938873 -75.156937
3                      The Gables Cafe  39.944194 -75.209709
4                     Restaurant Ambra  39.940324 -75.149300
5                            Caffe Ida  39.924223 -75.175689
6                Tortilleria San Roman  39.937636 -75.158082
7                          Lucatelli's  39.951761 -75.169130
8  Chiquita's Pizzeria & Mexican Grill  39.922904 -75.159634
9               Superior Pasta Company  39.939154 -75.158038

## Restaurants stats ##

In [81]:
restaurants_eda_df_full = pd.read_csv("stats/restaurant_eda_df_full.csv")

/var/folders/fd/585jf60x39vflmpy4gfz7yzh0000gn/T/ipykernel_17345/3909869273.py:1: DtypeWarning: Columns (16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  restaurants_eda_df_full = pd.read_csv("stats/restaurant_eda_df_full.csv")

In [155]:
restaurants_eda_df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52268 entries, 0 to 52267
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      52268 non-null  int64
 1   key_0             52268 non-null  object
 2   Unnamed: 0        52268 non-null  int64
 3   index             52268 non-null  int64
 4   business_id       52268 non-null  object
 5   postal_code       52247 non-null  object
 6   latitude          52268 non-null  float64
 7   longitude         52268 non-null  float64
 8   stars             52268 non-null  float64
 9   review_count      52268 non-null  int64
 10  is_open           52268 non-null  int64
 11  food_type         52268 non-null  object
 12  delivery          49672 non-null  object
 13  alcohol           52268 non-null  bool
 14  bike_parking      52234 non-null  object
 15  credit_card       52242 non-null  object
 16  appointment_only  52267 non-null  object
 17  caters            52221 non-null  object
 18  coat_check        52266 non-null  object
 19  dogs              52254 non-null  object
 20  drive_thru        51901 non-null  object
 21  good_for_kids     52268 non-null  int64
 22  good_for_groups   52268 non-null  int64
 23  happy_hour        52268 non-null  int64
 24  tv                52268 non-null  int64
 25  outdoor_seating   52268 non-null  int64
 26  price_range       52252 non-null  object
 27  reservations      52268 non-null  int64
 28  table_service     52268 non-null  int64
 29  take_out          52268 non-null  int64
 30  wheelchair        52268 non-null  int64
 31  city              52268 non-null  object
 32  state             52268 non-null  object
dtypes: bool(1), float64(3), int64(14), object(15)
memory usage: 12.8+ MB

In [86]:
from ff_app import selected_city

2024-09-03 11:11:47.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.814 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.816 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:47.894 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:48.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-09-03 11:11:48.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
/Users/dima/code/Dimasaur/scorecast/frontend/ff_app.py:135: DtypeWarning: Columns (16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  restaurants_eda_df_full = pd.read_csv("stats/restaurant_eda_df_full.csv")

In [111]:
restaurants_eda_df_full.isna().sum()

Unnamed: 0.1           0
key_0                  0
Unnamed: 0             0
index                  0
business_id            0
postal_code           21
latitude               0
longitude              0
stars                  0
review_count           0
is_open                0
food_type              0
delivery            2596
alcohol                0
bike_parking          34
credit_card           26
appointment_only       1
caters                47
coat_check             2
dogs                  14
drive_thru           367
good_for_kids          0
good_for_groups        0
happy_hour             0
tv                     0
outdoor_seating        0
price_range           16
reservations           0
table_service          0
take_out               0
wheelchair             0
city                   0
state                  0
dtype: int64

In [158]:
restaurants_eda_df_full.dtypes

Unnamed: 0.1          int64
key_0                object
Unnamed: 0            int64
index                 int64
business_id          object
postal_code          object
latitude            float64
longitude           float64
stars               float64
review_count          int64
is_open               int64
food_type            object
delivery             object
alcohol                bool
bike_parking         object
credit_card          object
appointment_only     object
caters               object
coat_check           object
dogs                 object
drive_thru           object
good_for_kids         int64
good_for_groups       int64
happy_hour            int64
tv                    int64
outdoor_seating       int64
price_range          object
reservations          int64
table_service         int64
take_out              int64
wheelchair            int64
city                 object
state                object
dtype: object

In [159]:
selected_city_df = restaurants_eda_df_full[restaurants_eda_df_full.city.astype(str).str.upper() == selected_city]
selected_city_df.columns

selected_city_stats = selected_city_df.drop(columns = ['Unnamed: 0.1', 'key_0', 'Unnamed: 0', 'index', 'business_id',
       'postal_code', 'latitude', 'longitude']).reset_index().drop(columns=['index'])

bool_col = selected_city_stats.select_dtypes(include="object").drop(columns=["food_type","price_range","city","state"])
bool_col_name = bool_col.columns
# clean up the na/nan values from the boolean columns

selected_city_stats[bool_col_name] = selected_city_stats[bool_col_name].fillna(False)
selected_city_stats[bool_col_name].isna().sum()

selected_city_stats[bool_col_name] = selected_city_stats[bool_col_name].astype(int)
selected_city_stats['alcohol'] = selected_city_stats['alcohol'].astype(int)

/var/folders/fd/585jf60x39vflmpy4gfz7yzh0000gn/T/ipykernel_17345/2494062020.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  selected_city_stats[bool_col_name] = selected_city_stats[bool_col_name].fillna(False)

In [160]:
selected_city_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   stars             45 non-null     float64
 1   review_count      45 non-null     int64
 2   is_open           45 non-null     int64
 3   food_type         45 non-null     object
 4   delivery          45 non-null     int64
 5   alcohol           45 non-null     int64
 6   bike_parking      45 non-null     int64
 7   credit_card       45 non-null     int64
 8   appointment_only  45 non-null     int64
 9   caters            45 non-null     int64
 10  coat_check        45 non-null     int64
 11  dogs              45 non-null     int64
 12  drive_thru        45 non-null     int64
 13  good_for_kids     45 non-null     int64
 14  good_for_groups   45 non-null     int64
 15  happy_hour        45 non-null     int64
 16  tv                45 non-null     int64
 17  outdoor_seating   45 non-null     int64
 18  price_range       44 non-null     object
 19  reservations      45 non-null     int64
 20  table_service     45 non-null     int64
 21  take_out          45 non-null     int64
 22  wheelchair        45 non-null     int64
 23  city              45 non-null     object
 24  state             45 non-null     object
dtypes: float64(1), int64(20), object(4)
memory usage: 8.9+ KB

In [166]:
int_col = selected_city_stats.select_dtypes(include="int").columns
int_col

Index(['review_count', 'is_open', 'delivery', 'alcohol', 'bike_parking',
       'credit_card', 'appointment_only', 'caters', 'coat_check', 'dogs',
       'drive_thru', 'good_for_kids', 'good_for_groups', 'happy_hour', 'tv',
       'outdoor_seating', 'reservations', 'table_service', 'take_out',
       'wheelchair'],
      dtype='object')

In [170]:
selected_city_stats[int_col].sum().sort_values(ascending = False)

review_count        831
take_out             38
is_open              34
good_for_kids        33
good_for_groups      30
tv                   28
bike_parking         22
reservations         19
alcohol              17
delivery             16
caters               10
outdoor_seating      10
table_service         5
wheelchair            5
happy_hour            3
credit_card           3
drive_thru            2
coat_check            1
dogs                  0
appointment_only      0
dtype: int64